name: Verify

on: [push]

jobs:
  base:
    name: Prepare
    runs-on: ubuntu-latest

    container:
      image: node:12.10.0-alpine
      volumes:
        - app_volume:$HOME

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node dependencies
        run: npm ci --production=false

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: base

    container:
      image: node:12.10.0-alpine
      volumes:
        - app_volume:$HOME

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Run tests
        run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: base

    container:
      image: node:12.10.0-alpine
      volumes:
        - app_volume:$HOME

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: base

    container:
      image: node:12.10.0-alpine
      volumes:
        - app_volume:$HOME

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Build
        run: npm run build
