name: Verify

on:
  pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node dependencies
        run: npm ci --production=false
      - name: Run tests
        run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: What's my base?
        run: echo "${{ github.event.pull_request.base.ref }}"
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node dependencies
        run: npm ci --production=false
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
          echo ::add-path::$(go env GOPATH)/bin # for Go projects
      - name: Lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run lint:ci | reviewdog -f=checkstyle -name=Lint -reporter=github-pr-check

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node dependencies
        run: npm ci --production=false
      - name: Build
        run: npm run build
